source 'http://rubygems.org'
ruby ENV['CUSTOM_RUBY_VERSION'] || '~> 2.3.2'

gem 'sinatra', :require => 'sinatra/base'
gem 'json'
gem 'faraday'
gem 'nokogiri'
gem 'pony'
gem 'mongo'
gem 'bson_ext'
gem 'resque'
gem 'rake'
